### ISSUE TITLE
Macros only execute if indented

### ISSUE THREAD

**Issue by lajohnston** [vhelin/wla-dx#310] opened 2020-05-13 20:20 UTC
Hi there,

I want to run a macro at the top level of a file but it didn't seem to be working. After trial and error it turns out the macro only executes if the call is indented by at least one space, i.e:

```
.macro "foo"
    .print "Bar\n"
.endm

 foo  ; this runs, note the space at start of line
foo   ; this won't run
````

Is this a known behaviour?

**Comment by vhelin** [comment] 2020-05-13 20:41
Yes, well, all strings that are placed at the beginning of the line, and are not directives, are considered as labels. It's been there for quite a while.

But I guess we could make macro calls work in this case. Though it might be a bit confusing for those who live by the old rule...

**Comment by Kroc** [comment] 2020-05-14 11:02
Most assemblers operate with the notion of a "gutter"; text that is _not_ indented is a definition, typically a label. Text that _is_ indented is the content, typically the assembly syntax. Some assemblers require there be a colon to define a label, but some rely on the guttering to determine what is and isn't a label, ala, the issue you're running into here.

**Comment by lajohnston** [comment] 2020-05-14 19:43
Ah interesting, ok I guess it might muddy the waters if it had a special exception for this, not without macros having their own syntax like `foo()` at least. The indentation's not the end of the world and I can keep it in with a comment to remind me. Thanks for clarifying!

**Comment by vhelin** [comment] 2020-05-15 19:45
This is actually a duplicate of issue #85 - https://github.com/vhelin/wla-dx/issues/85

Perhaps it might be worth making macro calls to work without leading whitespace as this old requirement seems to cause confusion...

**Closed** 2020-05-31 20:23 UTC
Labels: duplicate, enhancement, question

**Comment by lajohnston** [comment] 2020-06-01 17:24
Thanks! :)
